### PR TITLE
Add partial doctorName index

### PR DESCRIPTION
**Pull request by konpap99**
I added a partial index for user documents that contain  non null doctorRef.
It is based only in the lastname because it didnt make sense to me to added firstname too as we dont probably have doctors with same second name. however we could add it, no big deal

In order for mongo to use the index when you query you have to search only for documents with non null doctorRef fields as well

### CODE REVIEW

**Comment by nerdsupremacist** [comment]
@konpap99 so we're supposed to search for users by their name, and then for the doctor profile?

I'm not super sure if that will work, since search right now is directly using the doctor collection to perform other filters. Do you know how we can use both?

**Comment by konpap99** [comment]
After searching for doctor users we can get the Id of the selected doctor and use it to query doctor collection. So is there a need to combine them both?

**Comment by konpap99** [comment]
Important Note: In the text index documentation it says that "A collection can have at most one text index."
Here we already have to text indexes.
Inside compass I can see only the index that I first entered (firsName _lastName index).

However the search when entering a query containing e.g. "Hamburg"  returns correct results as well
image

I dont really know what is happening behind the scenes but it works :-)

**Comment by nerdsupremacist** [comment]
Confirmed it works with the names:

```graphql
{
	search(query: "Prohl") {
    results {
      edges {
        node {
          firstname
          lastname
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "search": {
      "results": {
        "edges": [
          {
            "node": {
              "firstname": "Inga",
              "lastname": "Pröhl"
            }
          }
        ]
      }
    }
  }
}
```

**Review by nerdsupremacist — APPROVED** [review]

**Pull request merged**
